import { getStandardDrumMusicXML } from './mockData';

export interface ScanSheetMusicOptions {
  base64Data: string; // The raw base64 string
  mimeType: string;   // e.g. "image/jpeg", "image/png", "application/pdf"
  systemPrompt?: string;
}

export async function scanSheetMusic({ base64Data, mimeType, systemPrompt }: ScanSheetMusicOptions): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    console.warn("GEMINI_API_KEY is not defined. Using mock fallback data.");
    // Simulate API delay to show processing logs in UI
    await new Promise(resolve => setTimeout(resolve, 3500));
    return getStandardDrumMusicXML("Scannet Trommenode (Demo Fallback)", 110, "standard");
  }

  const defaultPrompt = `Du er en ekspert i Optical Music Recognition (OMR) og trommenoder.
Analysér det vedhæftede billede eller PDF af en trommenode og transskriber den til en gyldig, komplet MusicXML 4.0-streng.

Vigtige regler:
1. Returner KUN den rå XML-streng uden nogen Markdown-formatering eller forklaringer (ingen \`\`\`xml tags eller lignende).
2. Noderne skal være skrevet i percussion clef (trommenoder) i 4/4 takt.
3. Brug standard General MIDI trommenotations-standarder (f.eks. display-step C5 og display-octave 5 for lilletromme (snare), F4/4 for stortromme (kick), G5/5 med krydshoved for hi-hat osv.).
4. Sørg for at XML-strukturen er komplet med <score-partwise>, <part-list>, <measure> osv., og at den kan fortolkes af OpenSheetMusicDisplay (OSMD).`;

  const prompt = systemPrompt || defaultPrompt;

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          contents: [
            {
              parts: [
                {
                  text: prompt,
                },
                {
                  inlineData: {
                    mimeType: mimeType,
                    data: base64Data,
                  },
                },
              ],
            },
          ],
          generationConfig: {
            responseMimeType: "text/plain",
          },
        }),
      }
    );

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();
    let text = data.candidates?.[0]?.content?.parts?.[0]?.text || "";

    if (!text) {
      throw new Error("No response content generated by Gemini.");
    }

    // Clean up any markdown code blocks wrapper that models sometimes generate anyway
    text = text.trim();
    if (text.startsWith("```")) {
      // remove leading ```xml or ```
      text = text.replace(/^```[a-zA-Z]*/, "");
      // remove trailing ```
      text = text.replace(/```$/, "");
    }
    
    return text.trim();
  } catch (error) {
    console.error("Error in scanSheetMusic:", error);
    throw error;
  }
}
